### ISSUE TITLE
Does it work on MAC?

### ISSUE THREAD

**Issue by ebisbe** [juharris/switch-remoteplay#12]
Hey,  

I was searching for a project like this and I want to try it out. I'm on a mac so some things are like linux. Do you know if it does not work?

If it works I can help with some JS UX development.

**Comment by juharris** [comment]
I'm not sure. I suggest you try to run https://github.com/mart1nro/joycontrol first and if that works then this should too. I'd be happy to know!

**Comment by ebisbe** [comment]
It does not work easily if it really works. Too much workarounds for Bluetooth configuration... I borrowed my fathers Raspberry and worked 1st try.
