### ISSUE TITLE
Can't connect to server with web client

### ISSUE THREAD

**Issue by DQuittard** [juharris/switch-remoteplay#30]
Hi, firstly I'm thankful for your tool !

So, I have a computer running Lubuntu, I've been able to setup the server as you explain.
But I can't seem to connect with any other computer.
I'm only successful with the localhost.

I tried connecting with my local IP adress (both of my PC are on the same wifi network), but the program gave me an error 400: code 400, message Bad request version

I can't seem to understand, apparently I have to use the http or https protocol ?
I'm wondering what I have to do to be able to connect...

Am I stupid or am I just unlucky ahah ?

Thanks by advance.

**Comment by juharris** [comment]
Thanks for trying the project! 
This can be tricky to debug because it could be a few things. To connect from another machine, you might need to enable Mixed/insecure content for the webpage. You can look up how to do that for your browser but it usually involves clicking on the lock next to the URL in your browser address bar and going to some advanced settings. 
Are you using the jubuntu webpage that I linked to in the README?

**Comment by DQuittard** [comment]
Yes I'm using your jubuntu webpage.
To be specific, I can't seem to use my controller (Xbox One wired) with the localhost, but I can use the keyboard or the buttons with the mouse.

I also allowed mixed/insecure content from your webpage by clicking on the shield in Firefox (I'll see if I find more settings though).

I saw in one of your videos that you had a raspberry pi, and that its adress was something like http://raspberrypi:port, would you mind explaining how you connected to it ? Perhaps it could help me, I'm not sure.

**Comment by DQuittard** [comment]
Okay so, you were right, I thought I had disabled mixed content but for some reason it wasn't ? It instantly worked on the same network !

Now though, the webapp can't seem to recogniez any of my USB controller.
Should I open a separate issue ?

I'm just wondering why, because keyboard is working perfectly !

**Comment by juharris** [comment]
That's very weird that the keyboard works but not the controller. Does the controller appear as an option in the dropdown on my page?

**Comment by juharris** [comment]
For getting my raspberry pi name, I believe you run the `hostname` command in your Linux terminal. You might also to be able to see you device names in your router's settings.

**Comment by juharris** [comment]
For the issues with the controller, do you see any messages in the developer console in your Firefox browser? I think you do Ctrl+Shift+J to open it.

**Comment by juharris** [comment]
Did you get the controller working?

**Comment by juharris** [comment]
This should be resolved in #39, otherwise please re-open.

**Comment by juharris** [comment]
For getting the controller working, feel free to file another issue. You have to move the joysticks or press a button on the controller to get it to show as an option in the dropdown. That's just how it has to work.
