### ISSUE TITLE
 code 400, message Bad request version

### ISSUE THREAD

**Issue by MrSimsure** [juharris/switch-remoteplay#34]
Hello, i was trying to make this work, i used to make it run some weeks ago, but now every time i try to connect from the client i get the error message of the title "`code 400, message Bad request version`" then a series of random letters and numbers.
Here some info of my setup : 
- i'm using a raspberry pi where my server is running, everything has been installed has the README said
- for the client i used this ready version "https://jubuntu.eastus.cloudapp.azure.com/" but also using the docker version give the same result both using a remote ip to my raspi or the local one.
- i already enabled the mixed content for that page, in fact the console doesn't give me the mixed content error, but this one:`
polling-xhr.js:268 GET my_raspy_ip:5000/socket.io/?EIO=3&transport=polling&t=NPTfQiO net::ERR_SSL_PROTOCOL_ERROR`
- During another test i got an error in the raspi console, but i can't get it to appear again, it said something about the client socket.io version being wrong or something like that i can't remember correctly.

What can be causing this error? Something in my setup or a client code problem?
Thank.

**Comment by juharris** [comment]
Thanks for trying out the project! Did you re-run this setup? Maybe flask-socketio is being picky? I can try out something in a few days but if you or someone else gets to it first, it would be good to specify specific version numbers in setup.py. Try using version 4.3.0 for flask-socketio. So running: `sudo pip3 install flask-socketio==4.3.0` might solve the issue.

**Comment by juharris** [comment]
This should be resolved in #39, otherwise please re-open.
