### ISSUE TITLE
Feature Request: Deadzones

### ISSUE THREAD

**Issue by DelxHQ** [juharris/switch-remoteplay#38]
It's quite hard to play animal crossing as my Xbox controller seems to drift off to the right a tiny bit. 

Possible to add user defined dead zones into the clinet?

**Comment by juharris** [comment]
Thanks for trying out the project! I noticed slight issues with my controller but it didn't bother me much. I added the option for setting deadzones by using URL params. So add `leftStickDeadzone=0.1` to the URL. For example: `http://jubuntu.eastus.cloudapp.azure.com/?a=http://raspberrypi:5000&leftStickDeadzone=0.1`. The website shows the full details about the URL params. Let me know how it works out for you and I can adjust how it works.
