### ISSUE TITLE
Questions about video streaming

### ISSUE THREAD

**Issue by lilynet336** [juharris/switch-remoteplay#81]
Hi, I have a few quick questions regarding how the video streaming portion works. 
1. In the network diagram in the README, it seems like the web client handles receiving the video, but as far as I can tell this isn't correct. Can you point me either way?
2. How exactly *do* I set up the video streaming? I have an RTSP/RTMP/HLS server that I can use, but does switch-remoteplay have to understand this setup? Or is the streaming portion independent?
3. If it *is* independent, how did you accomplish your very low latency? I have had good experiences with LL-HLS before but I am curious to try other protocols. 

Thank you!

**Comment by juharris** [comment]
I used Microsoft Mixer or Twitch for streaming.
